[DEBUG] [2019-03-30 23:44:39,728] [File 'error.py', line 125, in log_and_exit_handler] - LocalWorker-4: caught signal SIGINT, exiting
