From 2e32ae9942f5fddbefa08cc83174ac84340dd8ed Mon Sep 17 00:00:00 2001
From: Din Jakupi <din.jakupi@gmail.com>
Date: Wed, 28 Apr 2021 09:18:39 +0200
Subject: [PATCH] fix error/warning in setup install

---
 pypykatz/alsadecryptor/packages/kerberos/decryptor.py | 2 +-
 setup.py                                              | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/pypykatz/alsadecryptor/packages/kerberos/decryptor.py b/pypykatz/alsadecryptor/packages/kerberos/decryptor.py
index 5912efd..a5ba850 100644
--- a/pypykatz/alsadecryptor/packages/kerberos/decryptor.py
+++ b/pypykatz/alsadecryptor/packages/kerberos/decryptor.py
@@ -84,7 +84,7 @@ def handle_ticket(self, kerberos_ticket):
 		except Exception as e:
 			raise e
 	
-	def start(self):
+	async def start(self):
 		try:
 			entry_ptr_value, entry_ptr_loc = self.find_first_entry()
 		except Exception as e:
diff --git a/setup.py b/setup.py
index 427ccc7..707b933 100644
--- a/setup.py
+++ b/setup.py
@@ -45,11 +45,11 @@
 
 	# long_description=open("README.txt").read(),
 	python_requires='>=3.6',
-	classifiers=(
+	classifiers=[
 		"Programming Language :: Python :: 3.6",
 		"License :: OSI Approved :: MIT License",
 		"Operating System :: OS Independent",
-	),
+	],
 	install_requires=[
 		'minidump>=0.0.17',
 		'minikerberos>=0.2.11',
